name: 'dbt_demo'

version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_demo:
    staging:
      customer:
        +materialized: table
      employee:
        +materialized: table
      order:
        +materialized: table
    int:
      custo_order:
        +materialized: view
    mart:
      crm:
        +materialized: table